server:
  port: ${PORT:8888}
spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI:C:\Users\Geralt\IdeaProjects\gb-settings}
          clone-on-start: true
          username: ${GIT_USERNAME:geek}
          password: ${GIT_PASSWORD:geek}
        default-label: master
  security:
    user:
      name: ${SECURITY_USER:geek_user}
      password: ${SECURITY_PASSWORD:geek_pass}


#localhost:8888/[application_name]/[profile]/[label]
#
#localhost:8888/[gb-shop]/[dev]

